FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
COPY apps/merchant-portal/package.json apps/merchant-portal/package.json
RUN npm install
COPY . .
RUN npm run build --workspace=merchant-portal
EXPOSE 3001
CMD ["npm", "run", "start", "--workspace=merchant-portal", "--", "-p", "3001"]
