FROM node:20-alpine AS base
WORKDIR /app
COPY package*.json ./
COPY apps/api/package.json apps/api/package.json
RUN npm install

COPY . .
RUN npm run prisma:generate --workspace=api
RUN npm run build --workspace=api

EXPOSE 4000
CMD ["npm", "run", "start", "--workspace=api"]
